#!/bin/bash
# source ~/bin/clockinclockout/timeFunctions
source ./clockinclockout/timeFunctions

filename=$(get_recent_file_name)
if test -f "$filename"; then
  lastLine=$(get_last_line)
  if [ $lastLine  == "ci" ]; then
    result=$(convert_secs $(calculate_time))
    echo "You're already clocked in and been working for $result"
    exit 0
  fi
fi

write_time ci

time=$(date +"%R")
echo "Welcome back! Clocked in at $time"


