#!/bin/bash
# source ~/bin/clockinclockout/timeFunctions
source ./clockinclockout/timeFunctions

filename=./clockinclockout/$(date +"%F").txt
lastLine=""
if test -f "$filename"; then
  while read line; do
    lastLine=$line
  done < $filename

  read -a str_arr <<< "$lastLine"
  if [ ${str_arr[0]} == "ci" ]; then
    result=$(convert_secs $(calculate_time))
    echo "You're already clocked in and been working for $result"
    exit 0
  fi
fi

write_time ci

time=$(date +"%R")
echo "Welcome back! Clocked in at $time"


