#!/bin/bash

write_time() {
  now=$(date +"%s")
#  echo "$1 $now" >> ~/bin/clockinclockout/$file_name
  echo "$1 $now" >> $(get_recent_file_name)
}

calculate_time() {
  clockLog=./clockinclockout/$(date +"%F").txt
  if test -f "$clockLog"; then
    lastClockedIn=0
    lastClockedout=0
    while read line; do
      read -a clocked_arr <<< "$line"
      if [ ${clocked_arr[0]} == "ci" ]; then
        lastClockedIn=${clocked_arr[1]}
      fi
      if [ ${clocked_arr[0]} == "co" ]; then
        lastClockedOut=${clocked_arr[1]}
      fi
    done < $clockLog
    if [ lastClockedIn > lastClockedOut ]; then
      lastClockedOut=$(date +"%s")
    fi
    echo $((lastClockedOut-lastClockedIn))
  else
    return 0
  fi
}

get_recent_file_name() {
  fileName=$(date +"%F").txt
  echo ./clockinclockout/$fileName
}

convert_secs() {
  time=$1
  hours=$((time/3600))
  minutes=$(((time/60)%60))
  seconds=$((time%60))
  echo $hours:$minutes:$seconds
}

get_last_line() {
  filename=$(get_recent_file_name)
  if test -f "$filename"; then
    lastLine=""
    while read line; do
      lastLine=$line
    done < $filename

    read -a str_arr <<< "$lastLine"
    echo ${str_arr[0]}
  else
    echo 
  fi
}
